# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8bcf0519c503cc9562d62641e22908c34eb611175170565612b183a4fb5b24fa2a1d3363cfa5d90e61863049459a5aa286ffcd762abb659d5d5ff1ade556465

test:
  secret_key_base: d739d71f32d86bb9dd42aaa96f63df7611dfc5a3e8b644b23bc4dd9a36554c3b028dc3cb9fdbd6274d46325588703d14426dd57e759a108fa492c8095eb7ac9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
